// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.0
// source: phone.proto

package phone

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidPhoneByNumber struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PhoneNumber string `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
}

func (x *ValidPhoneByNumber) Reset() {
	*x = ValidPhoneByNumber{}
	if protoimpl.UnsafeEnabled {
		mi := &file_phone_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidPhoneByNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidPhoneByNumber) ProtoMessage() {}

func (x *ValidPhoneByNumber) ProtoReflect() protoreflect.Message {
	mi := &file_phone_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidPhoneByNumber.ProtoReflect.Descriptor instead.
func (*ValidPhoneByNumber) Descriptor() ([]byte, []int) {
	return file_phone_proto_rawDescGZIP(), []int{0}
}

func (x *ValidPhoneByNumber) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

type ValidatedPhone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PhoneNumber string `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Valid       bool   `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	CountryCode string `protobuf:"bytes,3,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
}

func (x *ValidatedPhone) Reset() {
	*x = ValidatedPhone{}
	if protoimpl.UnsafeEnabled {
		mi := &file_phone_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidatedPhone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatedPhone) ProtoMessage() {}

func (x *ValidatedPhone) ProtoReflect() protoreflect.Message {
	mi := &file_phone_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatedPhone.ProtoReflect.Descriptor instead.
func (*ValidatedPhone) Descriptor() ([]byte, []int) {
	return file_phone_proto_rawDescGZIP(), []int{1}
}

func (x *ValidatedPhone) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *ValidatedPhone) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidatedPhone) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

var File_phone_proto protoreflect.FileDescriptor

var file_phone_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70,
	0x68, 0x6f, 0x6e, 0x65, 0x22, 0x37, 0x0a, 0x12, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x50, 0x68, 0x6f,
	0x6e, 0x65, 0x42, 0x79, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x68,
	0x6f, 0x6e, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x6c, 0x0a,
	0x0e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x64, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x12,
	0x21, 0x0a, 0x0c, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x72, 0x79, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x32, 0x50, 0x0a, 0x0c, 0x50,
	0x68, 0x6f, 0x6e, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x40, 0x0a, 0x0a, 0x63,
	0x68, 0x65, 0x63, 0x6b, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x19, 0x2e, 0x70, 0x68, 0x6f, 0x6e,
	0x65, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x42, 0x79, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x1a, 0x15, 0x2e, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x2e, 0x56, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x64, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x22, 0x00, 0x42, 0x26, 0x5a,
	0x24, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2f, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x3b,
	0x70, 0x68, 0x6f, 0x6e, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_phone_proto_rawDescOnce sync.Once
	file_phone_proto_rawDescData = file_phone_proto_rawDesc
)

func file_phone_proto_rawDescGZIP() []byte {
	file_phone_proto_rawDescOnce.Do(func() {
		file_phone_proto_rawDescData = protoimpl.X.CompressGZIP(file_phone_proto_rawDescData)
	})
	return file_phone_proto_rawDescData
}

var file_phone_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_phone_proto_goTypes = []any{
	(*ValidPhoneByNumber)(nil), // 0: phone.ValidPhoneByNumber
	(*ValidatedPhone)(nil),     // 1: phone.ValidatedPhone
}
var file_phone_proto_depIdxs = []int32{
	0, // 0: phone.PhoneService.checkPhone:input_type -> phone.ValidPhoneByNumber
	1, // 1: phone.PhoneService.checkPhone:output_type -> phone.ValidatedPhone
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_phone_proto_init() }
func file_phone_proto_init() {
	if File_phone_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_phone_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ValidPhoneByNumber); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_phone_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ValidatedPhone); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_phone_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_phone_proto_goTypes,
		DependencyIndexes: file_phone_proto_depIdxs,
		MessageInfos:      file_phone_proto_msgTypes,
	}.Build()
	File_phone_proto = out.File
	file_phone_proto_rawDesc = nil
	file_phone_proto_goTypes = nil
	file_phone_proto_depIdxs = nil
}
